'use client';

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';

import { RoughNotation, RoughNotationGroup } from 'react-rough-notation';

const About = () => {
  return (
    <div id="about" className="w-full md:h-screen p-2 flex items-center py-16">
      <div className="max-w-screen-lg mx-auto md:grid grid-cols-3 gap-8">
        <div className="col-span-2">
          <p className="uppercase text-xl tracking-widest text-[#67eef3]">
            About
          </p>
          <h2 className="py-4">Who I Am</h2>
          <RoughNotationGroup show={true}>
            <p className="py-2 text-gray-100">
              As a computer science student at the University of Washington, I
              am passionate about using technology, specifically{' '}
              <RoughNotation type="highlight" color="#c0c039">
                artificial intelligence
              </RoughNotation>{' '}
              and{' '}
              <RoughNotation type="highlight" color="#9e00c9">
                machine learning
              </RoughNotation>
              , to solve real-world problems in various interdisciplinary fields
              such as medicine and political science. I have gained a strong
              foundation in programming, software development, and machine
              learning through my coursework and internship experiences,
              including developing mobile apps and websites using cutting-edge
              frameworks and libraries and using NLP to contextualize large
              datasets.
            </p>
            <p className="py-2 text-gray-100">
              I am proficient in languages such as C/C++, C#, Java/Kotlin,
              JavaScript/TypeScript, Python, and Rust, and have experience with
              web development libraries/frameworks like{' '}
              <RoughNotation type="highlight" color="#00a5c9">
                React.js
              </RoughNotation>
              , Next.js,{' '}
              <RoughNotation type="highlight" color="#00c954">
                Tailwindcss
              </RoughNotation>
              , and Node.JS. I am excited to continue learning and using my
              skills to make a positive impact through my work as a developer.
            </p>
            <p className="py-2 italic text-gray-400">
              - Generated by ChatGPT 2023
            </p>

            <p className="py-2">
              Currently looking for internship opportunities! {" "}
              <RoughNotation type="circle">Contact me.</RoughNotation>
            </p>
            <Link href="/#projects">
              <p className="py-2 text-gray-100 underline cursor-pointer">
                Check out some of my latest projects.
              </p>
            </Link>
          </RoughNotationGroup>
        </div>
        <div className="w-[300px] h-auto m-auto shadow-lg shadow-gray-200 rounded-xl flex items-center px-0 justify-center hover:scale-[1.02] ease-in duration-300">
          <Image
            src="/logo.jpg"
            width={300}
            height={300}
            className="rounded-xl"
            alt="/"
          />
        </div>
      </div>
    </div>
  );
};

export default About;
